legend: | # multi line string
    Программа для сведения итогов одиноковых файлов
    выберите пункт меню для работы:

folder: none # variable

filter: # dictionary
    sheet: #l ist
      - Титульный лист # list item
      - 1. Сведения об ОО
      - 2. Сведения об обучающихся
      - 3. Сведения о режиме работы ГПД
      - 4. Сведения о помещениях
      - 5. Сведения о кадрах
      - 6. Финансирование